---
- name: "Upgrade NextCloud Apps | {{ item.name }}"
  become: true
  become_user: "{{ nextcloud_user }}"
  command:
    chdir: "{{ item.path }}"
    cmd: php occ app:update --all
  register: upgrade_nextcloud_app
  changed_when: upgrade_nextcloud_app.stdout != ""

- name: "Upgrade NextCloud Core | {{ item.name }}"
  become: true
  become_user: "{{ nextcloud_user }}"
  command:
    chdir: "{{ item.path }}"
    cmd: php updater/updater.phar --no-interaction
  register: upgrade_nextcloud_core
  changed_when: "'No update available.' not in upgrade_nextcloud_core.stdout"
